name: Deploy on Heroku

on:
  push:
    branches:
      - master

jobs:
  heroku-deploy:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "owl-detect"
          heroku_email: "ilhamsyahids@gmail.com"
